version: '3.9'

services:
  wordpress:
    build:
      context: ./wordpress/docker/
    environment:
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./wordpress/html:/var/www/html
    depends_on:
      - db
    restart: always

  db:
    platform: linux/x86_64
    build:
      context: ./db/docker/
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./db/mysql:/var/lib/mysql

  proxy:
    build:
      context: ./proxy/docker/
    ports:
      - '8000:80'
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/conf.d:/etc/nginx/conf.d
      - ./proxy/log:/var/log/nginx
      - ./wordpress/html:/var/www/html
    depends_on:
      - wordpress
    restart: always